name: Deploy demo-app to Github-Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy demo-app
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BASE_PATH: /tailwind-datepicker-react

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Get files
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        working-directory: ./demo-app
        run: npm i
      - name: Build project
        working-directory: ./demo-app
        run: npm run build
      - name: Export static files
        working-directory: ./demo-app
        run: npm run export
      - name: Add .nojekyll file
        working-directory: ./demo-app
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: ./demo-app/out
